<?php

// UTF-8 translated language names
$mlp['lang'] = array( 'en' => 'English',
                      'de' => 'Deutsch',
                      'da' => 'Dansk',
                      'es' => 'Español',
                      'fr' => 'Français',
                      'fi' => 'Suomalainen',
                      'cs' => 'čeština',
                      'cz' => 'Česky',
                      'sk' => 'Slovenský',
                      'nl' => 'Nederlands',
                      'is' => 'Íslensku',
                      'tr' => 'Türk',
                      'se' => 'svenska',
                      'pt' => 'Português brasileiro',
                      'pt_PT' => 'Português Europeu',
                      'bg' => 'български',
                      'hu' => 'Magyar',
                      'no' => 'norsk',
                      'pl' => 'Polskie',
                      'ro' => 'Română',
                      'it' => 'italiano',
                      'ru' => 'русский',
                      'fa' => 'پارسی',
                      'tw' => '繁體中文',
                      'tn' => '繁體中文',
                      'zh' => '繁体中文',
                      'cn' => '繁体中文',
                      'ja' => '日本語',
                      'ko' => '한국어',
                      'sa' => 'العربية',
                      'ta' => 'தமிழ்');
