<?php

// translated language names
$mlp['lang'] = array( 'en' => 'English',
                      'de' => 'Deutsch',
                      'da' => 'Dansk',
                      'es' => 'Español',
                      'fr' => 'Français',
                      'fi' => 'Suomalainen',
                      'cs' => 'ceština',
                      'cz' => 'Cesky',
                      'sk' => 'Slovenskı',
                      'nl' => 'Nederlands',
                      'is' => 'Íslensku',
                      'tr' => 'Türk',
                      'se' => 'svenska',
                      'pt' => 'Português brasileiro',
                      'pt_PT' => 'Português Europeu',
                      'bg' => 'bulgarski',
                      'hu' => 'Magyar',
                      'no' => 'norsk',
                      'pl' => 'Polskie',
                      'ro' => 'Româna',
                      'it' => 'italiano',
                      'ru' => 'russkiy',
                      'fa' => 'Farsi',
                      'tw' => 'Fánti zhongwén',
                      'tn' => 'Fánti zhongwén',
                      'zh' => 'Fánti zhongwén',
                      'cn' => 'Fánti zhongwén',
                      'ja' => 'Nihongo',
                      'ko' => 'hangug-eo',
                      'sa' => 'eurbaa',
                      'ta' => 'Tamil');
