<?php

/**
 *  @author Vladimír Ajgl <vlada@ajgl.cz>
 *  EN-Revision: Revision of lang_en.inc.php
 *  Translated on 2007/11/30
 */

@define('PLUGIN_MYMOOD_TITLE',                  'Moje nálada');
@define('PLUGIN_MYMOOD_DESC',                   'Umoòuje vám pøidávat vaší momentální náladu nebo nálady k pøíspvìkùm.');
@define('PLUGIN_MYMOOD_MOOD_MISSINGDATA',       'Chybí uivatelskı vstup');
@define('PLUGIN_MYMOOD_MOOD_LIST',              'Toto je seznam pøístupnıch nálad.');
@define('PLUGIN_MYMOOD_MOOD_NAME',              'Jméno nálady');
@define('PLUGIN_MYMOOD_MOOD_IMG',               'Obrázek nálady.  (Relativní adresa vzheldem k základnímu adresáøi serendipity nebo plná absolutní URL adresa)');
@define('PLUGIN_MYMOOD_MOOD_ASCII',             'Textová repreznetace smajlíka nálady');
@define('PLUGIN_MYMOOD_MOOD_DELETE',            'Samzat');
@define('PLUGIN_MYMOOD_CONFIRM_RESET_BUTTON',   'Obnovit pùvodní nálady');
@define('PLUGIN_MYMOOD_CONFIRM_RESET',          'Opravdu chcete obnovit pùvodní nálady? Tento pøíkaz smae všechny Vaše nastavené nálady a nastaví místo nich pøednastavené.  \n\nVAROVÁNÍ: Smazání Vámi nastavenıch nálad mùe vést k zobrazování špatnıch nálad u starıch pøíspìvkù!');

@define('PLUGIN_MYMOOD_INTRO',                  'Intro');
@define('PLUGIN_MYMOOD_INTRO_DESC',             'Intro je text, kterı uvozuje seznam Vaší nálady. Napøíklad "Moje nálada:"');
@define('PLUGIN_MYMOOD_OUTRO',                  'Outro');
@define('PLUGIN_MYMOOD_OUTRO_DESC',             'Podobnì jako intro text');
@define('PLUGIN_MYMOOD_TODAY_I_FEEL',           'Moje nálada:');
@define('PLUGIN_MYMOOD_PLACE_FIELD',            'Umístít blízko');
@define('PLUGIN_MYMOOD_PLACE_FIELD_DESC',       'Poblí které èásti pøíspìvku se má nálada zobrazit?');
@define('PLUGIN_MYMOOD_PLACE_FIELD_BODY',       'Tìlo pøíspìveku');
@define('PLUGIN_MYMOOD_PLACE_FIELD_AUTHOR',     'Autor');
@define('PLUGIN_MYMOOD_PLACE_FIELD_TITLE',      'Nadpis');
@define('PLUGIN_MYMOOD_PLACE_FIELD_FOOTER',     'Záhlaví');
@define('PLUGIN_MYMOOD_PLACE_BEFORE',           'Umístit pøed');
@define('PLUGIN_MYMOOD_PLACE_BEFORE_DESC',      'Umístit náladu pøed vybrané pole? Pokud je vybráno NE, umístí se za pole.');
@define('PLUGIN_MYMOOD_DISPLAY_FORMAT',         'Formát zobrazení');
@define('PLUGIN_MYMOOD_DISPLAY_FORMAT_DESC',    'Formát zobrazení nálady. Mùete ouít pole {name}, {img} a {ascii} v jakémkoliv poøadí a mnoství k zobrazení nálad podle Vašich pøání. Toto nebude mít vliv na umístìní nálady v nadpisu. Mùete zadávat i hteml. (Standardnì: {img} {name})');
@define('PLUGIN_MYMOOD_MORE_NEW_MOODS',         'Další nové nálady');
@define('PLUGIN_MYMOOD_NEW_MOOD',               'Nová nálada (název)');
@define('PLUGIN_MYMOOD_NEW_ASCII',              'Text - smajlík');
@define('PLUGIN_MYMOOD_NEW_IMAGE',              'Obrázek (cesta)');

@define('PLUGIN_MYMOOD_ACCOMPLISHED'    , 'dokonalı      ');
@define('PLUGIN_MYMOOD_AGGRAVATED'      , 'pøitìující   ');
@define('PLUGIN_MYMOOD_AMUSED'          , 'pobavenı      ');
@define('PLUGIN_MYMOOD_ANGRY'           , 'zuøivı        ');
@define('PLUGIN_MYMOOD_ANNOYED'         , 'rozmrzelı     ');
@define('PLUGIN_MYMOOD_ANXIOUS'         , 'úzkostlivı    ');
@define('PLUGIN_MYMOOD_APATHETIC'       , 'otupìlı       '); 
@define('PLUGIN_MYMOOD_ARTISTIC'        , 'múzou políbenı'); 
@define('PLUGIN_MYMOOD_AWAKE'           , 'bdící         '); 
@define('PLUGIN_MYMOOD_BITCHY'          , 'hanebnı       '); 
@define('PLUGIN_MYMOOD_BLAH'            , 'kecy          '); 
@define('PLUGIN_MYMOOD_BLANK'           , 'prázdno       '); 
@define('PLUGIN_MYMOOD_BORED'           , 'znudìnı       '); 
@define('PLUGIN_MYMOOD_BOUNCY'          , 'ivı          '); 
@define('PLUGIN_MYMOOD_BUSY'            , 'zaneprázdnìnı '); 
@define('PLUGIN_MYMOOD_CALM'            , 'tichı         '); 
@define('PLUGIN_MYMOOD_CHEERFUL'        , 'veselı        '); 
@define('PLUGIN_MYMOOD_CHIPPER'         , 'nastrouhanı   '); 
@define('PLUGIN_MYMOOD_COLD'            , 'chladnı       ');
@define('PLUGIN_MYMOOD_COMPLACENT'      , 'uspokojenı    ');
@define('PLUGIN_MYMOOD_CONFUSED'        , 'zmatenı       ');
@define('PLUGIN_MYMOOD_CONTEMPLATIVE'   , 'zahloubanı    ');
@define('PLUGIN_MYMOOD_CONTENT'         , 'spokojenı     ');
@define('PLUGIN_MYMOOD_CRANKY'          , 'potrhlı       ');
@define('PLUGIN_MYMOOD_CRAPPY'          , 'posranı       ');
@define('PLUGIN_MYMOOD_CRAZY'           , 'bláznivı      ');
@define('PLUGIN_MYMOOD_CREATIVE'        , 'nápaditı      ');
@define('PLUGIN_MYMOOD_CRUSHED'         , 'zdrcenı       ');
@define('PLUGIN_MYMOOD_CURIOUS'         , 'zvìdavı       ');
@define('PLUGIN_MYMOOD_CYNICAL'         , 'cynickı       ');
@define('PLUGIN_MYMOOD_DEPRESSED'       , 'depka         ');
@define('PLUGIN_MYMOOD_DETERMINED'      , 'odhodlanı     ');
@define('PLUGIN_MYMOOD_DEVIOUS'         , 'odolnı        ');
@define('PLUGIN_MYMOOD_DIRTY'           , 'špinavı       ');
@define('PLUGIN_MYMOOD_DISAPPOINTED'    , 'znechucenı    ');
@define('PLUGIN_MYMOOD_DISCONTENT'      , 'nespokojenı   ');
@define('PLUGIN_MYMOOD_DISTRESSED'      , 'zoufalı       ');
@define('PLUGIN_MYMOOD_DITZY'           , 'šílenı        ');
@define('PLUGIN_MYMOOD_DORKY'           , 'vymaštìnı     ');
@define('PLUGIN_MYMOOD_DRAINED'         , 'vyèerpanı     ');
@define('PLUGIN_MYMOOD_DRUNK'           , 'opilı         ');
@define('PLUGIN_MYMOOD_ECSTATIC'        , 'nadšenı       ');
@define('PLUGIN_MYMOOD_EMBARRASSED'     , 'rozpaèitı     ');
@define('PLUGIN_MYMOOD_ENERGETIC'       , 'ráznı         ');
@define('PLUGIN_MYMOOD_ENRAGED'         , 'vztelkı       ');
@define('PLUGIN_MYMOOD_ENTHRALLED'      , 'fascinovanı   ');
@define('PLUGIN_MYMOOD_ENVIOUS'         , 'závistivı     ');
@define('PLUGIN_MYMOOD_EXANIMATE'       , 'bezduchı      ');
@define('PLUGIN_MYMOOD_EXCITED'         , 'vzrušenı      ');
@define('PLUGIN_MYMOOD_EXHAUSTED'       , 'uštvanı       ');
@define('PLUGIN_MYMOOD_FLIRTY'          , 'flirtující    ');
@define('PLUGIN_MYMOOD_FRUSTRATED'      , 'frustrovanı   ');
@define('PLUGIN_MYMOOD_FULL'            , 'naplnìnı      ');
@define('PLUGIN_MYMOOD_GEEKY'           , 'klaunskı      ');
@define('PLUGIN_MYMOOD_GIDDY'           , 'splašenı      ');
@define('PLUGIN_MYMOOD_GIGGLY'          , 'hihòám se     ');
@define('PLUGIN_MYMOOD_GLOOMY'          , 'skleslı       ');
@define('PLUGIN_MYMOOD_GOOD'            , 'dobrı         ');
@define('PLUGIN_MYMOOD_GRATEFUL'        , 'pøíjemnı      ');
@define('PLUGIN_MYMOOD_GROGGY'          , 'grogy         ');
@define('PLUGIN_MYMOOD_GRUMPY'          , 'mrzutı        ');
@define('PLUGIN_MYMOOD_GUILTY'          , 'provinilı     ');
@define('PLUGIN_MYMOOD_HAPPY'           , 'šastnı       ');
@define('PLUGIN_MYMOOD_HIGH'            , 'vysokı        ');
@define('PLUGIN_MYMOOD_HOPEFUL'         , 'slibnı        ');
@define('PLUGIN_MYMOOD_HORNY'           , 'nadrenı      ');
@define('PLUGIN_MYMOOD_HOT'             , 'havı         ');
@define('PLUGIN_MYMOOD_HUNGRY'          , 'hladovı       ');
@define('PLUGIN_MYMOOD_HYPER'           , 'hyper         ');
@define('PLUGIN_MYMOOD_IMPRESSED'       , 'ohromenı      ');
@define('PLUGIN_MYMOOD_INDESCRIBABLE'   , 'nepopsatelnı  ');
@define('PLUGIN_MYMOOD_INDIFFERENT'     , 'neutrální     ');
@define('PLUGIN_MYMOOD_INFURIATED'      , 'rozvzteklenı  ');
@define('PLUGIN_MYMOOD_INTIMIDATED'     , 'vystrašenı    ');
@define('PLUGIN_MYMOOD_IRATE'           , 'rozzlobenı    ');
@define('PLUGIN_MYMOOD_IRRITATED'       , 'podrádìnı    ');
@define('PLUGIN_MYMOOD_JEALOUS'         , 'árlivı       ');
@define('PLUGIN_MYMOOD_JUBILANT'        , 'vítìzoslavnı  ');
@define('PLUGIN_MYMOOD_LAZY'            , 'línı          ');
@define('PLUGIN_MYMOOD_LETHARGIC'       , 'letargie      ');
@define('PLUGIN_MYMOOD_LISTLESS'        , 'mdlı          ');
@define('PLUGIN_MYMOOD_LONELY'          , 'osamìlı       ');
@define('PLUGIN_MYMOOD_LOVED'           , 'milovanı      ');
@define('PLUGIN_MYMOOD_MELANCHOLY'      , 'zádumèivı     ');
@define('PLUGIN_MYMOOD_MELLOW'          , 'zralı         ');
@define('PLUGIN_MYMOOD_MISCHIEVOUS'     , 'uliènickı     ');
@define('PLUGIN_MYMOOD_MOODY'           , 'náladovı      ');
@define('PLUGIN_MYMOOD_MOROSE'          , 'nevrlı        ');
@define('PLUGIN_MYMOOD_NAUGHTY'         , 'sprostı       ');
@define('PLUGIN_MYMOOD_NAUSEATED'       , 'hnusnı        ');
@define('PLUGIN_MYMOOD_NERDY'           , 'blbı          ');
@define('PLUGIN_MYMOOD_NERVOUS'         , 'nervózní      ');
@define('PLUGIN_MYMOOD_NOSTALGIC'       , 'nostalgickı   ');
@define('PLUGIN_MYMOOD_NUMB'            , 'prokøehlı     ');
@define('PLUGIN_MYMOOD_OKAY'            , 'oukej         ');
@define('PLUGIN_MYMOOD_OPTIMISTIC'      , 'optimistickı  ');
@define('PLUGIN_MYMOOD_PEACEFUL'        , 'poklidnı      ');
@define('PLUGIN_MYMOOD_PENSIVE'         , 'zamyšlenı     ');
@define('PLUGIN_MYMOOD_PESSIMISTIC'     , 'pesimistickı  ');
@define('PLUGIN_MYMOOD_PISSED_OFF'      , 'obtìovanı    ');
@define('PLUGIN_MYMOOD_PLEASED'         , 'potìšenı      ');
@define('PLUGIN_MYMOOD_PREDATORY'       , 'krutı         ');
@define('PLUGIN_MYMOOD_PRETTY'          , 'krásnı        ');
@define('PLUGIN_MYMOOD_PRODUCTIVE'      , 'vıkonnı       ');
@define('PLUGIN_MYMOOD_QUIXOTIC'        , 'donkichotskı  ');
@define('PLUGIN_MYMOOD_RECUMBENT'       , 'odpoèívající  ');
@define('PLUGIN_MYMOOD_REFRESHED'       , 'obèerstvenı   ');
@define('PLUGIN_MYMOOD_REJECTED'        , 'odmítnutı     ');
@define('PLUGIN_MYMOOD_REJUVENATED'     , 'omlazenı      ');
@define('PLUGIN_MYMOOD_RELAXED'         , 'odpoèatı      ');
@define('PLUGIN_MYMOOD_RELIEVED'        , 'uvolnìnı      ');
@define('PLUGIN_MYMOOD_RESTLESS'        , 'neklidnı      ');
@define('PLUGIN_MYMOOD_RUSHED'          , 'uhnanı        ');
@define('PLUGIN_MYMOOD_SAD'             , 'smutnı        ');
@define('PLUGIN_MYMOOD_SATISFIED'       , 'spokojenı     ');
@define('PLUGIN_MYMOOD_SCARED'          , 'vylekanı      ');
@define('PLUGIN_MYMOOD_SHOCKED'         , 'šokovanı      ');
@define('PLUGIN_MYMOOD_SICK'            , 'nemocnı       ');
@define('PLUGIN_MYMOOD_SILLY'           , 'bláznivı      ');
@define('PLUGIN_MYMOOD_SLEEPY'          , 'ospalı        ');
@define('PLUGIN_MYMOOD_SORE'            , 'bolístka      ');
@define('PLUGIN_MYMOOD_STRESSED'        , 'pøetíenı     ');
@define('PLUGIN_MYMOOD_SURPRISED'       , 'pøekvapenı    ');
@define('PLUGIN_MYMOOD_SYMPATHETIC'     , 'chápavı       ');
@define('PLUGIN_MYMOOD_THANKFUL'        , 'vdìènı        ');
@define('PLUGIN_MYMOOD_THIRSTY'         , 'íznivı       ');
@define('PLUGIN_MYMOOD_THOUGHTFUL'      , 'peèlivı       ');
@define('PLUGIN_MYMOOD_TIRED'           , 'unavenı       ');
@define('PLUGIN_MYMOOD_TOUCHED'         , 'uraenı       ');
@define('PLUGIN_MYMOOD_UNCOMFORTABLE'   , 'nepohodlnı    ');
@define('PLUGIN_MYMOOD_WEIRD'           , 'tajuplnı      ');
@define('PLUGIN_MYMOOD_WORKING'         , 'pracující     ');
@define('PLUGIN_MYMOOD_WORRIED'         , 'ustaranı      ');

