<?php

/**
 * English stopword list. Unlike German (where all nouns are capitalized),
 * English only capitalizes proper nouns - so the capitalization-based noun
 * heuristic from Stopwords::isStopword() doesn't work here. Instead, a large
 * negative list - function words, adverbs, adjectives, and especially verbs
 * in their correctly inflected forms - does most of the work.
 *
 * Verb inflection is NOT generated by naively appending suffixes (get+ing =
 * "geting" would be wrong), but rule-based via conjugate():
 *  - Final consonant doubling before -ing/-ed for monosyllabic verbs and
 *    verbs stressed on the final syllable (get -> getting, occur -> occurring)
 *  - Silent -e is dropped before -ing; for -ed, just "d" is appended
 *    (use -> using/used); exceptions like -ee/-oe/-ye keep the e
 *    (agree -> agreeing, dye -> dyeing)
 *  - Consonant+y -> "ies"/"ied" (try -> tries/tried), vowel+y stays unchanged
 *    (play -> plays/played)
 *  - -s/-x/-z/-ch/-sh -> "es" for third person (watch -> watches)
 *  - True irregular forms are listed explicitly (go -> went/gone), since
 *    these follow no rule
 *
 * Because inflection is rule-based, ongoing maintenance only ever requires
 * adding the *base form* of a new verb to VERB_BASES (or to IRREGULAR for
 * irregular inflection) - every word form is generated automatically.
 * That's the only maintenance this is designed to need.
 *
 * British English (verbs): rather than maintaining every form twice, it's
 * derived automatically from the American base form:
 *  - "-ize"/"-yze" -> "-ise"/"-yse" (realize -> realise, analyze -> analyse),
 *    including all inflected forms, automatically for EVERY verb with this
 *    ending
 *  - Verbs ending in vowel+"l" double the "l" before -ed/-ing in British
 *    English but not in American English (travel -> travelled/travelling
 *    BrE, traveled/traveling AmE) - handled via the short, explicit
 *    DUAL_L_VERBS list (the general doubling heuristic can't automate this,
 *    since both spellings are valid)
 *
 * British English (nouns/adjectives): these don't follow inflection rules,
 * so NOUN_ADJ_VARIANTS lists explicit American/British spelling pairs
 * (colour/color, centre/center, defence/defense, ...). Both the singular
 * and a regular plural ("+s") are generated automatically per pair.
 */
final class StopwordsEn
{
    /**
     * Irregular verbs: base => all relevant inflected forms.
     */
    private const IRREGULAR = [
        'be' => ['is', 'was', 'were', 'been', 'being', 'am', 'are'],
        'begin' => ['begins', 'began', 'begun', 'beginning'],
        'become' => ['becomes', 'became', 'becoming'],
        'break' => ['breaks', 'broke', 'broken', 'breaking'],
        'bring' => ['brings', 'brought', 'bringing'],
        'build' => ['builds', 'built', 'building'],
        'buy' => ['buys', 'bought', 'buying'],
        'catch' => ['catches', 'caught', 'catching'],
        'choose' => ['chooses', 'chose', 'chosen', 'choosing'],
        'come' => ['comes', 'came', 'coming'],
        'cut' => ['cuts', 'cutting'],
        'do' => ['does', 'did', 'done', 'doing'],
        'draw' => ['draws', 'drew', 'drawn', 'drawing'],
        'drive' => ['drives', 'drove', 'driven', 'driving'],
        'eat' => ['eats', 'ate', 'eaten', 'eating'],
        'get' => ['gets', 'got', 'gotten', 'getting'],
        'fall' => ['falls', 'fell', 'fallen', 'falling'],
        'feel' => ['feels', 'felt', 'feeling'],
        'find' => ['finds', 'found', 'finding'],
        'fly' => ['flies', 'flew', 'flown', 'flying'],
        'forget' => ['forgets', 'forgot', 'forgotten', 'forgetting'],
        'give' => ['gives', 'gave', 'given', 'giving'],
        'go' => ['goes', 'went', 'gone', 'going'],
        'grow' => ['grows', 'grew', 'grown', 'growing'],
        'have' => ['has', 'had', 'having'],
        'hear' => ['hears', 'heard', 'hearing'],
        'hide' => ['hides', 'hid', 'hidden', 'hiding'],
        'hold' => ['holds', 'held', 'holding'],
        'keep' => ['keeps', 'kept', 'keeping'],
        'know' => ['knows', 'knew', 'known', 'knowing'],
        'lead' => ['leads', 'led', 'leading'],
        'leave' => ['leaves', 'left', 'leaving'],
        'let' => ['lets', 'letting'],
        'lose' => ['loses', 'lost', 'losing'],
        'make' => ['makes', 'made', 'making'],
        'mean' => ['means', 'meant', 'meaning'],
        'meet' => ['meets', 'met', 'meeting'],
        'pay' => ['pays', 'paid', 'paying'],
        'read' => ['reads', 'reading'],
        'ride' => ['rides', 'rode', 'ridden', 'riding'],
        'rise' => ['rises', 'rose', 'risen', 'rising'],
        'run' => ['runs', 'ran', 'running'],
        'see' => ['sees', 'saw', 'seen', 'seeing'],
        'sell' => ['sells', 'sold', 'selling'],
        'send' => ['sends', 'sent', 'sending'],
        'set' => ['sets', 'setting'],
        'shake' => ['shakes', 'shook', 'shaken', 'shaking'],
        'shoot' => ['shoots', 'shot', 'shooting'],
        'show' => ['shows', 'showed', 'shown', 'showing'],
        'sing' => ['sings', 'sang', 'sung', 'singing'],
        'sit' => ['sits', 'sat', 'sitting'],
        'sleep' => ['sleeps', 'slept', 'sleeping'],
        'speak' => ['speaks', 'spoke', 'spoken', 'speaking'],
        'spend' => ['spends', 'spent', 'spending'],
        'steal' => ['steals', 'stole', 'stolen', 'stealing'],
        'swim' => ['swims', 'swam', 'swum', 'swimming'],
        'stand' => ['stands', 'stood', 'standing'],
        'take' => ['takes', 'took', 'taken', 'taking'],
        'teach' => ['teaches', 'taught', 'teaching'],
        'tell' => ['tells', 'told', 'telling'],
        'think' => ['thinks', 'thought', 'thinking'],
        'throw' => ['throws', 'threw', 'thrown', 'throwing'],
        'understand' => ['understands', 'understood', 'understanding'],
        'wear' => ['wears', 'wore', 'worn', 'wearing'],
        'win' => ['wins', 'won', 'winning'],
        'write' => ['writes', 'wrote', 'written', 'writing'],
    ];

    /**
     * Regular verb base forms (everyday language + tech/blogging vocabulary
     * describing actions rather than topics - "installed", "configured",
     * "debugged" describe what the author did, not a tag-worthy subject).
     * All inflected forms are generated automatically via conjugate().
     * NOTE: 3-letter words here (act, lay, mob, rap, si, zip, ...)
     *       normally never become true because of the 4-letter char limit
     *       and so are just some no-cost safety net words like also in other
     *       sections or decribed as to be left in these list for safety.
     */
    private const VERB_BASES = [
        'accept','achieve','acquit','act','add','admit','affect','agree','aim','allot',
        'allow','announce','annul','appear','apply','approach','argue','arrange','arrive',
        'ask','attach','attack','attempt','attend','avoid','ban','bar','base','bat','beat',
        'bed','beg','behave','believe','belong','benefit','bid','blame','blow','bob',
        'boost','borrow','break','bug','bum','burn','bus','calculate','call','cancel',
        'cap','car','care','carry','cause','celebrate','challenge','change','channel',
        'check','claim','clean','clear','climb','close','collect','combine','commit',
        'communicate','compare','compel','compete','complain','complete','concern',
        'confirm','connect','consider','contact','contain','continue','contribute',
        'control','convince','cook','cop','copy','correct','counsel','count','cover',
        'crash','create','cross','cry','damage','dance','deal','decide','defer','deliver',
        'demand','deny','depend','describe','design','destroy','deter','develop','dial',
        'die','differ','dig','dip','disappear','discover','discuss','divide','dot','drag',
        'draw','dream','dress','drink','drive','drop','drum','earn','eat','educate',
        'elect','emerge','employ','encourage','end','engage','enjoy','enrol','ensure',
        'enter','equal','equip','escape','establish','estimate','examine','exist','expand',
        'expect','expel','experience','explain','explore','express','extend','extol',
        'face','fail','fan','fear','fight','file','fill','film','finish','fix','flip',
        'float','flop','flow','focus','follow','force','forgive','form','frighten','fuel',
        'gain','gather','generate','glance','govern','grab','greet','grin','grip',
        'guarantee','guess','guide','handle','hang','happen','hate','head','heat','help',
        'hide','hit','hold','hop','hope','hug','host','hunt','hurry','hurt','identify',
        'ignore','imagine','implement','improve','include','increase','incur','indicate',
        'infer','influence','inform','install','instil','intend','interest','interpret',
        'interrupt','introduce','invest','invite','involve','issue','jam','join','jog',
        'jot','jump','justify','kick','kill','knit','knock','knot','label','laugh',
        'launch','lay','learn','lend','level','lie','lift','light','limit','link','list',
        'listen','live','load','locate','lock','look','love','maintain','man','manage',
        'map','mark','marvel','match','matter','measure','mention','miss','mix','model',
        'mob','mop','move','nab','need','nod','note','notice','obtain','occur','offer',
        'omit','open','operate','order','organize','own','paint','pad','pat','participate',
        'pass','patrol','perceive','perform','permit','pick','pin','pit','place','plan',
        'plant','play','plot','plug','point','pop','pot','pour','practice','predict',
        'prefer','prepare','present','press','pretend','prevent','print','prod','produce',
        'program','promise','promote','protect','prove','provide','publish','pull','push',
        'put','puzzle','quarrel','question','quit','race','raise','reach','react',
        'realize','receive','recognize','recommend','quiz','rap','rebel','rebut','record',
        'recur','reduce','refer','reflect','refuse','regard','register','regret','reject',
        'relate','release','rely','remain','remember','remove','repair','repeat','repel',
        'replace','reply','report','represent','reproduce','require','respond','rest',
        'result','return','reveal','review','rib','rid','rig','rim','ring','rip','rise',
        'rival','rob','roll','rot','rub','rule','rush','sag','satisfy','save','say','scan',
        'scar','scare','score','scream','search','seek','seem','select','sell','separate',
        'serve','settle','shake','shape','share','shift','shine','ship','shock','shoot',
        'shop','shout','shred','shrug','shun','shut','sigh','sign','sin','signal',
        'simplify','sink','sip','skid','skim','skip','slam','slap','slide','slim','slip',
        'slit','slot','slug','smell','smile','snag','snap','snip','sob','solve','sort',
        'sound','spare','speak','spell','spin','split','spot','spread','spring','spur',
        'stab','star','stare','start','state','stay','stem','step','stick','stir','stop',
        'store','strap','strengthen','stretch','strike','strut','struggle','stub','study',
        'stun','submit','succeed','suffer','suggest','suit','sum','sun','supply','support',
        'suppose','surprise','survive','suspect','sustain','swap','switch','tag','talk',
        'tan','tap','target','taste','tend','terminate','thank','threaten','throb','tie',
        'tip','touch','trade','train','transfer','transform','translate','transmit',
        'transport','trap','trek','travel','treat','trigger','trip','top','trust','try',
        'tug','tunnel','turn','type','undertake','unite','update','upgrade','upset','urge',
        'use','vary','view','visit','vote','wait','wake','walk','want','warn','wash',
        'waste','wag','watch','wave','wed','weigh','welcome','whip','whiz','wish',
        'witness','wonder','work','worry','wrap','yield','zip',
        // Tech / blogging (Domain: GIT, Programming)
        'analyze','annotate','assess','authenticate','authorize','backup','bind',
        'cache','categorize','clarify','clone','comment','compile','compress',
        'compute','concatenate','configure','convert','customize','debug','decrypt',
        'delete','deploy','disconnect','document','download','duplicate','encrypt',
        'evaluate','excel','export','fetch','format','hash','highlight','import','inherit',
        'initialize','instantiate','integrate','iterate','log','loop','merge',
        'migrate','modify','monitor','optimize','override','parse','process','query',
        'rebuild','recurse','redesign','refactor','render','restore','restructure',
        'sanitize','strip','structure','subscribe','summarize','sync','synchronize',
        'toggle','trim','unbind','upload','validate','verify',
        // Digital/modern verbs (previously missing despite everyday use)
        'alert','autofill','autosave','block','bookmark','boot','bootstrap','browse',
        'checkout','click','downvote','embed','expire','filter','flag','fork','hook',
        'hydrate','inject','internationalize','invalidate','localize','moderate',
        'mount','mute','navigate','notify','orchestrate','paginate','paste','patch',
        'pause','ping','prefetch','preload','rate','rebase','reboot','redirect',
        'redo','refresh','reload','repost','reshare','resize','restart','resume',
        'retry','retweet','rewind','rollback','scale','scroll','stash','stream',
        'swipe','throttle','timeout','unblock','undo','unfollow','unmount','unpin',
        'upvote','zoom',
        // Additional "-ize" verbs (British "-ise" forms are derived automatically)
        'apologize','capitalize','centralize','characterize','containerize',
        'criticize','decentralize','deserialize','emphasize','familiarize','finalize',
        'generalize','harmonize','incentivize','maximize','memorize','minimize',
        'mobilize','modernize','modularize','monetize','normalize','popularize',
        'prioritize','randomize','serialize','specialize','stabilize','standardize',
        'synthesize','virtualize',
    ];

    /**
     * Verbs ending in vowel+"l" that double the "l" before -ed/-ing in
     * British English but not American English. Both forms are generated.
     */
    private const DUAL_L_VERBS = [
        'cancel','channel','counsel','dial','equal','fuel','label','level','marvel',
        'model','quarrel','rival','signal','travel','tunnel',
    ];

    /**
     * Curated list instead of algorithmic syllable detection (syllable
     * counting is unreliable in plain PHP - "happen" looks structurally
     * like "get" but doesn't double: "happening", not "happenning").
     */
    private const DOUBLING_VERBS = [
        'acquit','admit','allot','annul','ban','bar','bat','bed','beg','bid','bob',
        'bug','bum','bus','cap','car','commit','compel','control','cop','cut','debug',
        'defer','deter','dig','dip','dot','drag','drop','drum','enrol','equip',
        'excel','expel','extol','fan','fit','flip','flop','format','get','grab',
        'grin','grip','hit','hop','hug','incur','infer','instil','jam','jog','jot',
        'knit','knot','man','map','mob','mop','nab','nod','occur','omit','pad','pat',
        'patrol','permit','pin','pit','plan','plot','plug','pop','pot','prefer',
        'prod','program','put','quit','quiz','rap','rebel','rebut','recur','refer',
        'regret','repel','rib','rid','rig','rim','rip','rob','rot','rub','run','sag',
        'scan','scar','set','ship','shop','shred','shrug','shun','sin','sip','sit',
        'skid','skim','skip','slam','slap','slim','slip','slit','slot','slug','snag',
        'snap','snip','sob','spin','spot','spur','stab','star','stem','step','stir',
        'stop','strap','strip','strut','stub','stun','submit','sum','sun','swap',
        'swim','tag','tan','tap','throb','tip','top','transfer','transmit','trap',
        'trek','trim','trip','tug','upset','wag','wed','whip','whiz','win','wrap',
        'zip',
    ];

    /**
     * American/British spelling pairs for nouns and adjectives, which don't
     * follow a derivable inflection rule the way verbs do (unlike -ize/-ise,
     * there's no single pattern covering colour/color, centre/center,
     * defence/defense, etc.) - so both spellings are listed explicitly.
     * Both singular and a regular plural ("+s") are generated for each.
     */
    private const NOUN_ADJ_VARIANTS = [
        // -our / -or
        ['colour', 'color'], ['favour', 'favor'], ['behaviour', 'behavior'],
        ['honour', 'honor'], ['humour', 'humor'], ['labour', 'labor'],
        ['neighbour', 'neighbor'], ['rumour', 'rumor'], ['harbour', 'harbor'],
        ['endeavour', 'endeavor'], ['armour', 'armor'], ['vapour', 'vapor'],
        // -re / -er
        ['centre', 'center'], ['theatre', 'theater'], ['metre', 'meter'],
        ['litre', 'liter'], ['fibre', 'fiber'], ['calibre', 'caliber'],
        ['sombre', 'somber'],
        // -ce / -se
        ['defence', 'defense'], ['offence', 'offense'], ['licence', 'license'],
        ['pretence', 'pretense'],
        // -ogue / -og
        ['dialogue', 'dialog'], ['catalogue', 'catalog'], ['analogue', 'analog'],
        // Miscellaneous
        ['practise', 'practice'], ['grey', 'gray'], ['programme', 'program'],
        ['mould', 'mold'], ['sceptic', 'skeptic'], ['tyre', 'tire'],
        ['aluminium', 'aluminum'],
    ];

    /**
     * Words ending in "-ly" that are NOT adjective+ly adverbs (so must be
     * excluded from the blanket "-ly = manner adverb, therefore stopword"
     * rule below). Manner adverbs ("actively", "quickly", "centrally") are
     * almost never useful tags - they describe how something was done, not
     * what it's about - so they're treated as stopwords by default unless
     * listed here.
     */
    private const LY_EXCEPTIONS = [
        'ally','analogy','anomaly','apply','assembly','belly','bully','burly',
        'butterfly','comply','costly','daily','deadly','dragonfly','early','elderly',
        'family','firefly','fly','folly','friendly','fully','holy','homily','imply',
        'jolly','july','likely','lively','lonely','lovely','melancholy','monopoly',
        'monthly','multiply','only','orderly','ply','rally','rely','reply','silly',
        'supply','timely','ugly','weekly','yearly',
    ];

    public static function set(): array
    {
        static $words = null;
        if ($words !== null) {
            return $words;
        }

        // NOTE: single/two-letter entries here (a, i, be, in, hi, ...) never
        // actually get checked in practice at the default minWordLength=4 -
        // tokenize() filters anything shorter than that BEFORE calling
        // isStopword() at all. They're kept anyway as a no-cost safety net:
        // unlike short content words (see "eis"/"gas" in the German list,
        // or "CMS"/"SMS" as short tech acronyms), pure function words never
        // become useful tags no matter how low minWordLength is set, so
        // there's no scenario where listing them causes a false negative.
        $functionWords = [
            'a','about','actually','admittedly','after','again','against','ago','all',
            'almost','alone','already','also','always','among','an','and','any','anyone',
            'anything','anywhere','apparently','are','as','away','backward','barely',
            'basically','be','because','been','before','being','between','both','broadly',
            'but','can','certainly','clearly','could','currently','definitely','down',
            'during','each','easily','especially','essentially','even','eventually',
            'ever','every','everyone','everything','everywhere','fairly','few','finally',
            'for','forward','frequently','from','fundamentally','further','generally',
            'gradually','hardly','he','hello','her','here','hey','hi','him','his','how',
            'i','if','immediately','importantly','in','initially','instantly',
            'interestingly','into','is','it','its','just','later','like','may','maybe',
            'me','merely','might','more','most','must','my','nearly','never','no',
            'nobody','none','nor','normally','not','notably','nothing','now','nowhere',
            'obviously','occasionally','of','off','often','oh','ok','okay','on','once',
            'only','or','other','our','out','over','own','particularly','perhaps',
            'please','possibly','pretty','previously','primarily','probably','quickly',
            'quite','rapidly','rarely','rather','really','recently','regularly','same',
            'seemingly','shall','she','should','significantly','simply','slowly','so',
            'some','somebody','someone','something','sometimes','somewhat','somewhere',
            'soon','specifically','still','such','suddenly','supposedly','surprisingly',
            'than','thank','thanks','that','the','their','them','then','there','these',
            'they','this','those','through','to','today','together','tomorrow','too',
            'truly','typically','under','until','up','us','usually','very','was','we',
            'well','were','what','when','where','while','who','whom','whose','why','will',
            'with','without','would','year','years','yes','yesterday','yet','you','your',
            // Absolute possessive pronouns ("this is mine", not "my") and that are not already declared: (his)
            'hers','mine','ours','theirs','yours',
            // Reflexive pronouns
            'herself','himself','itself','myself','oneself','ourselves','themselves',
            'yourself','yourselves',
            // Quantifiers, that are not aleady listed like (all, some, more, no, any, most,
            //              each, few, both, every and each; In adjectives: plenty, several,)
            'another','either','enough','many','much','neither','one','which',
            // [+] Quantifiers in combinations with "of", colloquial forms, members of a group (combined with nouns)
            //     but not are too risky, i.e. colliding with valid tec tag words ( "load/loads" )
            'fewer','heaps','tons',
            // Connectors / discourse markers
            'although','anyhow','anyway','besides','furthermore','hence','however',
            'indeed','instead','meanwhile','moreover','nevertheless','nonetheless',
            'otherwise','therefore','though','thus','unless',
            // Formatting/markup artifacts (...spellings)
            'greater-than','less-than','line-through','linethrough','strike-through',
            'strikethrough',
            // Nouns too generic to ever be a meaningful tag
            'bit','bits','case','cases','kind','kinds','lot','lots','part','parts','sort',
            'sorts','stuff','thing','things','type','types','way','ways',
            // Blog meta words (the medium itself, not the topic - the English
            // counterpart to German "Beitrag", which was already filtered out)
            'article','articles','blog','blogs','entries','entry','href','post','posts',
        ];

        $adjectives = [
            'able','active','advanced','appropriate','assumption','automatic','available',
            'bad','basic','best','better','big','blank','central','certain','clear',
            'closed','common','complex','correct','current','custom','default',
            'different','difficult','direct','early','easy','economic','effective',
            'efficient','empty','enormous','false','free','full','general','good','great',
            'hard','helpful','high','human','important','inactive','incorrect','indirect',
            'inefficient','international','invalid','irrelevant','large','late','likely',
            'local','long','low','main','major','manual','minor','national','negative',
            'new','old','open','optional','other','own','particular','personal',
            'pleasantness','pleased','pleasing','pleasurable','political','positive',
            'possible','private','public','real','reasonable','recent','relevant',
            'required','right','same','several','short','significant','similar','simple',
            'small','social','specific','standard','strong','stupendous','suitable',
            'sure','tremendous','true','unenjoyable','useful','useless','valid','various',
            'voluminous','weak','whole','whopping','worse','worst','wrong','young',
            // '','','','','','',
            // Curated from a frequency-list review: generic evaluative/emotion/
            // quantity/sequence words with no topical content of their own.
            // Deliberately EXCLUDED from this batch (kept as valid potential
            // tags) - anything colour/material/texture/taste-related (food
            // blog relevance: sharp, raw, sweet, fresh, thick, rich, dry, ...),
            // geography/direction, occupations/roles, genres, or otherwise
            // topical nouns used adjectivally (chance, character, content,
            // key, novel, status, stock, ... vitality, infinity, attractive ...).
            'acceptable','according','accurate','actual','additional','administrative',
            'afraid','aggressive','alive','amazing','angry','annual','another','anxious',
            'apart','asleep','aware','beautiful','boring','born','brave','brief','bright',
            'brilliant','broad','busy','calm','capable','careful','cheap','comfortable',
            'competitive','comprehensive','confident','conscious','consistent','constant',
            'cool','crazy','critical','curious','cute','dangerous','dear','decent',
            'dependent','desperate','distinct','double','due','educational','embarrassed',
            'emotional','equivalent','exact','excellent','exciting','expensive',
            'external','extra','familiar','famous','final','fine','formal','former',
            'frequent','glad','grand','gross','guilty','honest','huge','hungry','ideal',
            'ill','immediate','impossible','impressive','individual','inevitable',
            'informal','initial','inner','inside','intelligent','internal','last',
            'latter','least','little','logical','lonely','loud','lower','lucky','mad',
            'massive','maximum','middle','minimum','narrow','nasty','nearby','neat',
            'necessary','nervous','next','nice','normal','numerous','objective','obvious',
            'odd','official','opposite','ordinary','outside','overall','past','perfect',
            'pleasant','plenty','plus','poor','popular','potential','powerful',
            'practical','previous','primary','prior','proper','proud','public','quiet',
            'ready','realistic','regular','remarkable','responsible','sad','safe',
            'scared','serious','severe','sick','silly','single','slight','sorry','spare',
            'special','straight','strange','strict','stupid','substantial','successful',
            'sudden','sufficient','super','suspicious','tall','technical','temporary',
            'terrible','tight','tiny','total','typical','ugly','unable','unfair',
            'unhappy','unique','unusual','upper','upstairs','usual','valuable','vast',
            'visible','weekly','weird','wide','willing','wise','wonderful','worth',
        ];

        $verbForms = [];
        foreach (self::VERB_BASES as $base) {
            foreach (self::conjugate($base) as $form) {
                $verbForms[] = $form;
            }

            // British English: derive "-ize"/"-yze" -> "-ise"/"-yse" automatically
            // (realize -> realise, analyze -> analyse), including all inflected
            // forms - no need to maintain both spellings by hand.
            if (preg_match('/(i|y)ze$/', $base)) {
                $britishBase = mb_substr($base, 0, -2) . 'se';
                foreach (self::conjugate($britishBase) as $form) {
                    $verbForms[] = $form;
                }
            }
        }
        foreach (self::DUAL_L_VERBS as $base) {
            // British "l" doubling (the American form is already produced via
            // VERB_BASES + conjugate(), since these verbs are listed there too)
            $verbForms[] = $base . 'led';
            $verbForms[] = $base . 'ling';
        }
        foreach (self::IRREGULAR as $base => $forms) {
            $verbForms[] = $base;
            foreach ($forms as $form) {
                $verbForms[] = $form;
            }
        }

        // British/American noun & adjective spelling variants, singular + plural
        $spellingVariants = [];
        foreach (self::NOUN_ADJ_VARIANTS as [$british, $american]) {
            $spellingVariants[] = $british;
            $spellingVariants[] = $british . 's';
            $spellingVariants[] = $american;
            $spellingVariants[] = $american . 's';
        }

        $words = array_fill_keys(
            array_merge($functionWords, $adjectives, $verbForms, $spellingVariants),
            true
        );
        return $words;
    }

    /**
     * Generates [base form, 3rd person singular, -ed form, -ing form] via rules.
     * @return string[]
     */
    private static function conjugate(string $base): array
    {
        $forms = [$base];
        $last = mb_substr($base, -1);
        $last2 = mb_substr($base, -2);
        $secondLast = mb_substr($base, -2, 1);

        // 3rd person singular
        if (preg_match('/(s|x|z|ch|sh)$/', $base)) {
            $forms[] = $base . 'es';
        } elseif ($last === 'y' && !self::isVowel($secondLast)) {
            $forms[] = mb_substr($base, 0, -1) . 'ies';
        } else {
            $forms[] = $base . 's';
        }

        // -ed form
        if ($last === 'e') {
            $forms[] = $base . 'd';
        } elseif ($last === 'y' && !self::isVowel($secondLast)) {
            $forms[] = mb_substr($base, 0, -1) . 'ied';
        } elseif (self::doublesConsonant($base)) {
            $forms[] = $base . $last . 'ed';
        } else {
            $forms[] = $base . 'ed';
        }

        // -ing form
        if ($last2 === 'ie') {
            $forms[] = mb_substr($base, 0, -2) . 'ying';
        } elseif ($last === 'e' && !in_array($last2, ['ee', 'oe', 'ye'], true)) {
            $forms[] = mb_substr($base, 0, -1) . 'ing';
        } elseif (self::doublesConsonant($base)) {
            $forms[] = $base . $last . 'ing';
        } else {
            $forms[] = $base . 'ing';
        }

        return $forms;
    }

    private static function isVowel(string $char): bool
    {
        return in_array(mb_strtolower($char), ['a', 'e', 'i', 'o', 'u'], true);
    }

    private static function doublesConsonant(string $base): bool
    {
        return in_array($base, self::DOUBLING_VERBS, true);
    }

    public static function isStopword(string $word): bool
    {
        $set = self::set();
        if (isset($set[$word])) {
            return true;
        }

        // Catch genitive/plural "s" (e.g. proper names: "allans" -> "allan")
        if (mb_strlen($word) > 2 && mb_substr($word, -1) === 's') {
            $stripped = mb_substr($word, 0, -1);
            if (isset($set[$stripped])) {
                return true;
            }
        }

        // Manner adverbs ("actively", "centrally", "quickly", "pleasurably")
        // are treated as stopwords by default - a word ending in "-ly" is
        // assumed to be an adjective+ly adverb unless it's on the LY_EXCEPTIONS allow-list
        // (words that natively end in "-ly" without being derived adverbs,
        // e.g. "family", "early", "friendly").
        if (mb_strlen($word) > 4 && mb_substr($word, -2) === 'ly'
            && !in_array($word, self::LY_EXCEPTIONS, true)) {
            return true;
        }

        return false;
    }
}